server.port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./data/fornecedor;INIT=RUNSCRIPT FROM 'classpath:data.sql';
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    initialize: true
    plataform: h2
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true

  eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka